In [1]:
import sys
sys.path.append('/Users/pradap/Documents/Research/Python-Package/enrique/')

In [2]:
import magellan as mg

DEBUG:Cloud:Log file (/Users/pradap/.picloud/cloud.log) opened


In [3]:
mg.test_variable()

Enter ltable: 


KeyError: ''

In [4]:
A = 10

In [5]:
mg.test_variable()

Enter ltable: A


KeyError: 'A'

In [6]:
globals()

{'A': 10,
 'In': ['',
  u"import sys\nsys.path.append('/Users/pradap/Documents/Research/Python-Package/enrique/')",
  u'import magellan as mg',
  u'mg.test_variable()',
  u'A = 10',
  u'mg.test_variable()',
  u'globals()'],
 'Out': {},
 '_': '',
 '__': '',
 '___': '',
 '__builtin__': <module '__builtin__' (built-in)>,
 '__builtins__': <module '__builtin__' (built-in)>,
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__name__': '__main__',
 '__package__': None,
 '_dh': [u'/Users/pradap/Documents/Research/Python-Package/enrique/notebooks/archive'],
 '_i': u'mg.test_variable()',
 '_i1': u"import sys\nsys.path.append('/Users/pradap/Documents/Research/Python-Package/enrique/')",
 '_i2': u'import magellan as mg',
 '_i3': u'mg.test_variable()',
 '_i4': u'A = 10',
 '_i5': u'mg.test_variable()',
 '_i6': u'globals()',
 '_ih': ['',
  u"import sys\nsys.path.append('/Users/pradap/Documents/Research/Python-Package/enrique/')",
  u'import magellan as mg',
  u'mg.test

In [31]:
A = mg.load_dataset('table_A')

In [32]:
A = A.to_dataframe()

In [33]:
A = A[['birth_year', 'hourly_wage', 'zipcode']]

In [27]:
l = [0]*len(A)

In [29]:
l[2] = 1
l[4] = 1

In [17]:
A['label'] = l

/Users/pradap/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [18]:
A

birth_year  hourly_wage  zipcode  label
0        1989         30.0    94107      0
1        1988         27.5    94122      0
2        1986         32.0    94107      1
3        1987         32.5    94122      0
4        1984         35.0    94122      1

In [20]:
import sklearn

In [21]:
# Convert DataFrame to matrix
mat = A.as_matrix()
# Using sklearn
km = sklearn.cluster.KMeans(n_clusters=2)
km.fit(mat)
# Get cluster assignment labels
labels = km.labels_
# Format results as a DataFrame
results = pandas.DataFrame([dataset.index,labels]).T

AttributeError: 'module' object has no attribute 'cluster'

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
lr = LogisticRegression()

In [34]:
A

birth_year  hourly_wage  zipcode
0        1989         30.0    94107
1        1988         27.5    94122
2        1986         32.0    94107
3        1987         32.5    94122
4        1984         35.0    94122

In [35]:
A.values

array([[  1.98900000e+03,   3.00000000e+01,   9.41070000e+04],
       [  1.98800000e+03,   2.75000000e+01,   9.41220000e+04],
       [  1.98600000e+03,   3.20000000e+01,   9.41070000e+04],
       [  1.98700000e+03,   3.25000000e+01,   9.41220000e+04],
       [  1.98400000e+03,   3.50000000e+01,   9.41220000e+04]])

In [30]:
lr.fit(A, l)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)

In [39]:
type(A)

pandas.core.frame.DataFrame

In [36]:
lr.coef_

array([[-0.43589949,  0.44159636,  0.00904812]])

In [37]:
lr.fit(A.values, l)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)

In [38]:
lr.coef_

array([[-0.43589949,  0.44159636,  0.00904812]])

In [43]:
sklearn.cross_validation.train_test_split(A, 0.5, 0.5)

TypeError: Singleton array array(0.5) cannot be considered a valid collection.

In [44]:
help(sklearn.cross_validation.train_test_split)

Help on function train_test_split in module sklearn.cross_validation:

train_test_split(*arrays, **options)
    Split arrays or matrices into random train and test subsets
    
    Quick utility that wraps input validation and
    ``next(iter(ShuffleSplit(n_samples)))`` and application to input
    data into a single call for splitting (and optionally subsampling)
    data in a oneliner.
    
    Parameters
    ----------
    *arrays : sequence of arrays or scipy.sparse matrices with same shape[0]
        Python lists or tuples occurring in arrays are converted to 1D numpy
        arrays.
    
    test_size : float, int, or None (default is None)
        If float, should be between 0.0 and 1.0 and represent the
        proportion of the dataset to include in the test split. If
        int, represents the absolute number of test samples. If None,
        the value is automatically set to the complement of the train size.
        If train size is also None, test size is set to 0.25.
    

In [47]:
a, b= sklearn.cross_validation.train_test_split(A, train_size=3, test_size=2)

In [50]:
b

birth_year  hourly_wage  zipcode
1        1988         27.5    94122
0        1989         30.0    94107

In [2]:
from sklearn.datasets import load_iris
from sklearn.cross_validation import cross_val_score
from sklearn.tree import DecisionTreeClassifier


In [7]:
import pandas as pd

In [3]:
clf = DecisionTreeClassifier()

In [4]:
iris = load_iris()

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
d = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [9]:
d

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9     

In [11]:
id(clf)

4400120208

In [10]:
clf.name = 'DecisionTree'

In [20]:
cross_val_score(clf, d, iris.target, cv=10, scoring='precision_weighted')

array([ 1.        ,  0.94444444,  1.        ,  0.94444444,  0.94444444,
        0.86666667,  0.94444444,  1.        ,  1.        ,  1.        ])

In [29]:
s = clf.__class__ .__name__

In [31]:
s

'DecisionTreeClassifier'

In [14]:
help(cross_val_score)

Help on function cross_val_score in module sklearn.cross_validation:

cross_val_score(estimator, X, y=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs')
    Evaluate a score by cross-validation
    
    Parameters
    ----------
    estimator : estimator object implementing 'fit'
        The object to use to fit the data.
    
    X : array-like
        The data to fit. Can be, for example a list, or an array at least 2d.
    
    y : array-like, optional, default: None
        The target variable to try to predict in the case of
        supervised learning.
    
    scoring : string, callable or None, optional, default: None
        A string (see model evaluation documentation) or
        a scorer callable object / function with signature
        ``scorer(estimator, X, y)``.
    
    cv : cross-validation generator or int, optional, default: None
        A cross-validation generator to use. If int, determines
        the number of folds in Stra